theme = "terminal"
baseurl = "https://fpgartktic.github.io/"
languageCode = "en-us"
pagination.pagerSize = 5

[markup.goldmark.renderer]
  unsafe = true

[params]
  contentTypeName = "posts"
  showMenuItems = 4
  fullWidthTheme = true
  centerTheme = false
  customCSS = ["assets/css/custom.css"]
# Główne menu dla motywu terminal
[[menu.main]]
  identifier = "about"
  name = "About me"
  url = "/about"
[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects"
[[menu.main]]
  identifier = "licensing"
  name = "Licensing"
  url = "/licensing"
[[menu.main]]
  identifier = "links"
  name = "Interesting links"
  url = "/links"


[languages]
  [languages.en]
    title = "FPGArktic"
    copyright = ""
    
    [languages.en.params]
      subtitle = "FPGArktic"
      keywords = ""
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read another posts"

    [languages.en.params.logo]
      logoText = "FPGArktic"
      logoHomeLink = "/"

[caches]
  [caches.images]
    dir = ":cacheDir/images"
